language: node_js
node_js:
  - 8
before_script:
  - npm install @11ty/eleventy -g
script: eleventy --pathprefix="/Dark-Portfolio-Template-11ty/"
deploy:
  #fqdn: jmschrack.dev
  local-dir: _site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure. Create token at (GitHub Profile)-Settings>Developer Settings>Personal Access
  keep-history: true
  target_branch: gh-pages # if running as a user profile page, change this to "master"
  on:
    branch: dev
